on:
  workflow_dispatch:
    inputs:
      releases_run_id:
        description: "Run ID of the release workflow, eg: 123456"
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download latest release artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.inputs.releases_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -R
